### ISSUE TITLE
Windows下用Ctex打不开thesis.tex等tex文件

### ISSUE THREAD

**Issue by zyzhong** [eclipselu/zjuthesis-mphil#2]
Windows下用Ctex打不开thesis.tex等tex文件，不过这个问题不大，可以用其他文本编辑器写，只是还是没有原来Ctex的编辑器好用

**Comment by eclipselu** [comment]
不好意思一直没看这个 issue，我记得因为CTeX自带的编辑器打不开 utf-8 编码的文件，由于不是特别严重的问题 ，我先关掉了哈。
