### ISSUE TITLE
封面图片编码问题

### ISSUE THREAD

**Issue by cstackess** [eclipselu/zjuthesis-mphil#3]
**问题：** 产生的log日志文件过大，发现是因为log日志文件中频繁出现类似`Invalid UTF-8 byte or sequence at line 138 replaced by U+FFFD.`的错误提示，即`\makeCoverPage`和`\makeECoverPage`命令行。

**解决：**  `CoverPagepic/`文件夹下的两个`eps`图片，采用ASCII编码，而我们的论文一般采用UTF-8编码。因此，可拿Adobe Acrobat软件由`pdf`重新存为UTF-8编码的图片。

**Comment by eclipselu** [comment]
@cstackess 多谢反馈，我回家看下，发现它还有一些其它问题，我一并更新下把。

**Comment by eclipselu** [comment]
修复了
