### ISSUE TITLE
Mac 字体问题

### ISSUE THREAD

**Issue by qqning** [eclipselu/zjuthesis-mphil#5]
使用Mac 的同学可能缺少Lisu和youyan字体。
首先安装对应字体，下载 [youyan_lisu.zip](https://github.com/eclipselu/zjuthesis-mphil/files/1810427/youyan_lisu.zip)并安装。

然后如下修改文件`/usr/local/texlive/2017/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-mac.def`（注意安装的texlive版本，我这里是**2017**）：
- 在`\setCJKfamilyfont { zhkai }  { STKaiti }`下面添加
```
\setCJKfamilyfont { zhli }    { LiSu }
\setCJKfamilyfont { zhyou }   { YouYuan }
```
- 在`\NewDocumentCommand \kaishu   { } { \CJKfamily { zhkai } }`后面添加
```
\NewDocumentCommand \lishu    { } { \CJKfamily { zhli } }
\NewDocumentCommand \youyuan  { } { \CJKfamily { zhyou } }
```

这样编译应该就没问题了，Good luck!

**Comment by eclipselu** [comment]
多谢！
