### ISSUE TITLE
编译看不到参考文献目录

### ISSUE THREAD

**Issue by ztjsw** [eclipselu/zjuthesis-mphil#6]
您好，我用vscode+latex插件能顺利编译代码（配置方式 https://zhuanlan.zhihu.com/p/38178015），但是目录里面就是看不到参考文献，请问需要什么额外的配置吗

**Comment by eclipselu** [comment]
多谢反馈 我等下看看

**Comment by eclipselu** [comment]
我自己试了一下是OK的，我的环境是 macOS 10.15.6, TeXLive 2019，你可不可以参考一下 https://github.com/eclipselu/zjuthesis-mphil/blob/master/typeset.sh 看看是不是忘了做 bibtex 

不行的话你可以先试试看 [如何使用](https://github.com/eclipselu/zjuthesis-mphil#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8) 的方法是不是能正常编译
如果可以的话，你可以看看是不是 VSCode 的插件配置有问题。

**Comment by eclipselu** [comment]
装了一下那个 [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) 插件在 VSCode 试了一下，也是可以的，用了如下的配置：

```json
"latex-workshop.latex.tools": [
    {
        "name": "xelatex",
        "command": "xelatex",
        "args": [
            "%DOCFILE%"
        ],
        "env": {}
    },
    {
        "name": "bibtex",
        "command": "bibtex",
        "args": [
            "%DOCFILE%"
        ],
        "env": {}
    }
],
"latex-workshop.latex.recipes": [
    {
        "name": "xe->bib->xe->xe",
        "tools": [
            "xelatex",
            "bibtex",
            "xelatex",
            "xelatex"
        ]
    },
],
```

**Comment by ztjsw** [comment]
感谢您及时回复和帮助，我现在可以编译出参考文献了。看起来是我之前没有做bibtex。谢谢！
